project: "BookBERT"
name: "clip_large"
config:
  lr: 1e-5
  architecture: "ClipLPbase"
  dataset: "DCM 400"
  epochs: 200
  dropout: 0.4
  batch_size: 248
  model_id: "openai/clip-vit-large-patch14"
  seed: 10
  augmentations: false
  num_aug_copies: 5
  num_synth_books: 1000
  num_attention_heads: 4
  num_hidden_layers: 4
  positional_embeddings: "absolute"
  hidden_dim: 256
  warmup: 44
  initial_lr: 1e-6