augmentations: true
batch_size: 16
dataset: DCM small
dropout_p: 0.23048252097178024
epochs: 200
hidden_dim: 512
initial_lr: 1.5706939983851608e-06
lr: 0.0007666024565470605
model_id: openai/clip-vit-large-patch14
num_attention_heads: 2
num_aug_copies: 6
num_hidden_layers: 6
num_synth_books: 1000
positional_embeddings: absolute
seed: 10
warmup: 80
